name: Hello World

on:
  push:
    branches:
      - main

jobs:
  first-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello World GA testing"
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello world of testing"

  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
            - name: Run tests
              run: pytest

      - name: Run tests
        run: pytest
