name: Test Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  java-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Compile Java
        run: javac HelloWorld.java
      - name: Run Java
        run: java HelloWorld | tee output.log
